export const dinnerIdeas = [
  "Espen special",
  "Gorm Special",
  "Vemund Special",
  "Håkon Special",
  "Spaghetti Bolognese",
  "Lasagne",
  "Kylling Tikka Masala",
  "Fiskekaker med poteter",
  "Laks med sitron og urter",
  "Torsk med sennepssaus",
  "Kjøttkaker i brun saus",
  "Biff med ovnsbakte grønnsaker",
  "Kyllingwok med grønnsaker",
  "Vegetarisk curry",
  "Pizza Margherita",
  "Pizza med pepperoni",
  "Pizza med skinke og ananas",
  "Tacograteng",
  "Taco",
  "Fajitas med kylling",
  "Fajitas med biff",
  "Kyllingvinger med dip",
  "Svinefilet med fløtesaus",
  "Lammestek med poteter",
  "Kyllingfilet med ovnsbakte rotgrønnsaker",
  "Grillet laks med ris",
  "Grillet torsk med grønnsaker",
  "Fiskegrateng",
  "Kjøttboller med pasta",
  "Pasta Carbonara",
  "Pasta Alfredo",
  "Pasta med pesto og kylling",
  "Ratatouille",
  "Vegetarisk lasagne",
  "Quiche med spinat og ost",
  "Quiche Lorraine",
  "Suppe med kylling og grønnsaker",
  "Tomatsuppe med pasta",
  "Kremet soppesuppe",
  "Kyllingsuppe med nudler",
  "Chili con carne",
  "Chili sin carne (vegetarisk)",
  "Burrito med bønner og ris",
  "Burrito med kjøtt",
  "Grønnsakswok med ris",
  "Pad Thai",
  "Stekt ris med grønnsaker",
  "Stekt ris med kylling",
  "Sushi",
  "Fish and chips",
  "Grillet kylling med salat",
  "Grillet pølse med brød",
  "Bacon og egg",
  "Omelett med skinke og ost",
  "Omelett med grønnsaker",
  "Pannekaker med bacon",
  "Pannekaker med syltetøy",
  "Rømmegrøt",
  "Kålruletter",
  "Fårikål",
  "Bacalao",
  "Lapskaus",
  "Kyllinggryte med kokosmelk",
  "Indisk dal",
  "Gul curry med kylling",
  "Gul curry med grønnsaker",
  "Grønnsakssuppe",
  "Tom kha gai (thailandsk kyllingsuppe)",
  "Kylling satay med peanøttsaus",
  "Svinewok med grønnsaker",
  "Kjøttgryte med poteter",
  "Fylte paprikaer",
  "Fylte squash",
  "Lasagne med spinat og ricotta",
  "Vegetarpizza med grønnsaker",
  "Torsk med tomatsaus og pasta",
  "Fiskesuppe med grønnsaker",
  "Gratinert torsk",
  "Gratinert laks",
  "Kylling schnitzel med potetsalat",
  "Schnitzel med grønnsaker",
  "Wienerschnitzel",
  "Svinestek med surkål",
  "Ribbe med medisterkaker",
  "Pinnekjøtt med kålrotstappe",
  "Kyllingfilet fylt med ost og skinke",
  "Kyllingfilet fylt med spinat",
  "Pasta med reker og fløtesaus",
  "Fettuccine med sopp og krem",
  "Kremet kyllingpasta",
  "Vegetarisk pasta med tomatsaus",
  "Kremet laksepasta",
  "Grønnsaksburger med salat",
  "Kyllingburger med dressing",
  "Fishburger",
  "Pizza med tre oster",
  "Pizza med kjøttboller",
  "Pizza med grønnsaker",
  "Pasta med kjøttsaus",
  "Pasta med tunfisk",
  "Risotto med sopp",
  "Risotto med sjømat",
  "Ratatouille med ris",
  "Kikertcurry",
  "Linsesuppe",
  "Vegetarisk chili",
  "Grønnsaksgrateng",
  "Bakt potet med fyll",
  "Bakt søtpotet med fyll",
  "Fylte tomater",
  "Tortilla med kjøtt og grønnsaker",
  "Tortilla med ost og grønnsaker",
];
